config/routes.rb
Rails.application.routes.draw do
  resources :remuneracoes
  resources :turnos
  resources :funcionarios

  root to: "home#index"
end

app/models/concerns/controllers/remuneracoes_controller.rb
class RemuneracoesController < ApplicationController
  before_action :set_remuneracao, only: [:show, :edit, :update, :destroy]

  # GET /remuneracoes
  # GET /remuneracoes.json
  def index
    @remuneracoes = Remuneracao.all
  end

  # GET /remuneracoes/1
  # GET /remuneracoes/1.json
  def show
  end

  # GET /remuneracoes/new
  def new
    @remuneracao = Remuneracao.new
  end

  # GET /remuneracoes/1/edit
  def edit
  end

  # POST /remuneracoes
  # POST /remuneracoes.json
  def create
    @remuneracao = Remuneracao.new(remuneracao_params)

    respond_to do |format|
      if @remuneracao.save
        format.html { redirect_to @remuneracao, notice: 'Remuneracao foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @remuneracao }
      else
        format.html { render :new }
        format.json { render json: @remuneracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remuneracoes/1
  # PATCH/PUT /remuneracoes/1.json
  def update
    respond_to do |format|
      if @remuneracao.update(remuneracao_params)
        format.html { redirect_to @remuneracao, notice: 'Remuneracao foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @remuneracao }
      else
        format.html { render :edit }
        format.json { render json: @remuneracao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remuneracoes/1
  # DELETE /remuneracoes/1.json
  def destroy
    @remuneracao.destroy
    respond_to do |format|
      format.html { redirect_to remuneracoes_url, notice: 'Remuneracao foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remuneracao
      @remuneracao = Remuneracao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def remuneracao_params
      params.require(:remuneracao).permit(:funcionario_id, :salario)
    end
end

app/helpers/remuneracoes_helper.rb
module RemuneracoesHelper
end

app/views/remuneracoes/_form.html.erb
<%= form_with(model: remuneracao, local: true) do |form| %>
  <% if remuneracao.errors.any? %>
    <div id="error_explanation">
      <h2>Confira os erros abaixo:</h2>

      <ul>
        <% remuneracao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.select(:funcionario_id, Funcionario.all.collect {|f| [f.nome, f.id]}) %>
  </div>

  <div class="field">
    <%= form.label :salario %>
    <%= form.number_field :salario %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/remuneracoes/edit.html.erb
<div class="content-wrapper container">
  <h1>Editando</h1>

  <%= render 'form', remuneracao: @remuneracao %>

  <%= link_to 'Mostrar', @remuneracao %> |
  <%= link_to 'Voltar', remuneracoes_path %>
</div>

app/views/remuneracoes/index.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <h1>Remunerações</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Funcionario</th>
        <th>Salario</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @remuneracoes.each do |remuneracao| %>
      <tr>
        <td><%= remuneracao.funcionario.nome %></td>
        <td><%= remuneracao.salario %></td>
        <td><%= link_to 'Mostrar', remuneracao %></td>
        <td><%= link_to 'Editar', edit_remuneracao_path(remuneracao) %></td>
        <td><%= link_to 'Apagar', remuneracao, method: :delete, data: { confirm: 'Você tem certeza ??' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_remuneracao_path, class: "btn btn-primary" %>
</div>

app/views/remuneracoes/new.html.erb
<div class="content-wrapper container">
  <h1>Novo</h1>

  <%= render 'form', remuneracao: @remuneracao %>

  <%= link_to 'Voltar', remuneracoes_path %>
</div>

app/views/remuneracoes/show.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Funcionario:</strong>
    <%= @remuneracao.funcionario_id %>
  </p>

  <p>
    <strong>Salario:</strong>
    <%= @remuneracao.salario %>
  </p>

  <%= link_to 'Editar', edit_remuneracao_path(@remuneracao) %> |
  <%= link_to 'Voltar', remuneracoes_path %>
</div>