config/routes.rb
Rails.application.routes.draw do
  resources :remuneracoes
  resources :turnos
  resources :funcionarios

  root to: "home#index"
end

app/models/concerns/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turno_params
      params.require(:turno).permit(:funcionario_id, :entrada, :saida)
    end
end

app/models/turno.rb
class Turno < ApplicationRecord
  belongs_to :funcionario
  validates :entrada, :saida, presence: true
end

app/controllers/turnos_controller.rb
class TurnosController < ApplicationController
  before_action :set_turno, only: [:show, :edit, :update, :destroy]

  # GET /turnos
  # GET /turnos.json
  def index
    @turnos = Turno.all
    if params[:funcionario_id].present?
      @turnos = @turnos.where(funcionario_id: params[:funcionario_id])
    end
  end

  # GET /turnos/1
  # GET /turnos/1.json
  def show
  end

  # GET /turnos/new
  def new
    @turno = Turno.new
  end

  # GET /turnos/1/edit
  def edit
  end

  # POST /turnos
  # POST /turnos.json
  def create
    @turno = Turno.new(turno_params)

    respond_to do |format|
      if @turno.save
        format.html { redirect_to @turno, notice: 'Turno foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @turno }
      else
        format.html { render :new }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnos/1
  # PATCH/PUT /turnos/1.json
  def update
    respond_to do |format|
      if @turno.update(turno_params)
        format.html { redirect_to @turno, notice: 'Turno foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @turno }
      else
        format.html { render :edit }
        format.json { render json: @turno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnos/1
  # DELETE /turnos/1.json
  def destroy
    @turno.destroy
    respond_to do |format|
      format.html { redirect_to turnos_url, notice: 'Turno foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turno
      @turno = Turno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def turno_params
      params.require(:turno).permit(:funcionario_id, :entrada, :saida)
    end
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/turnos/_form.html.erb
<%= form_with(model: turno, local: true) do |form| %>
  <% if turno.errors.any? %>
    <div id="error_explanation">
      <h2>Confira os erros abaixo:</h2>

      <ul>
        <% turno.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :funcionario_id %>
    <%= form.select(:funcionario_id, Funcionario.all.collect {|f| [f.nome, f.id]}) %>
  </div>

  <div class="field">
    <%= form.label :entrada %>
    <%= form.datetime_field :entrada %>
  </div>

  <div class="field">
    <%= form.label :saida %>
    <%= form.datetime_field :saida %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/turnos/edit.html.erb
<div class="content-wrapper container">
  <h1>Editando Turno</h1>

  <%= render 'form', turno: @turno %>

  <%= link_to 'Mostrar', @turno %> |
  <%= link_to 'Voltar', turnos_path %>
</div>

app/views/turnos/index.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <h1>Turnos</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Funcionario</th>
        <th>Entrada</th>
        <th>Saida</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @turnos.each do |turno| %>
      <tr>
        <td><%= turno.funcionario.nome %></td>
        <td><%= turno.entrada.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= turno.saida.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= link_to 'Mostrar', turno %></td>
        <td><%= link_to 'Editar', edit_turno_path(turno) %></td>
        <td><%= link_to 'Apagar', turno, method: :delete, data: { confirm: 'Você tem certeza ??' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_turno_path, class: "btn btn-primary" %>
</div>

app/views/turnos/new.html.erb
<div class="content-wrapper container">
  <h1>Novo</h1>

  <%= render 'form', turno: @turno %>

  <%= link_to 'Voltar', turnos_path %>
</div>

app/views/turnos/show.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Funcionario:</strong>
    <%= @turno.funcionario_id %>
  </p>

  <p>
    <strong>Entrada:</strong>
    <%= @turno.entrada.strftime("%d/%m/%Y %H:%M") %>
  </p>

  <p>
    <strong>Saida:</strong>
    <%= @turno.saida.strftime("%d/%m/%Y %H:%M") %>
  </p>

  <%= link_to 'Editar', edit_turno_path(@turno) %> |
  <%= link_to 'Voltar', turnos_path %>
</div>