config/routes.rb
Rails.application.routes.draw do
  resources :remuneracoes
  resources :turnos
  resources :funcionarios

  root to: "home#index"
end

app/models/concerns/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario foi apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome)
    end
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  validates :nome, presence: true

  def dias_trabalhados
    Turno.where(funcionario_id: self.id).where("EXTRACT(MONTH FROM entrada) = ?", Time.zone.now.month).count
  end
  
  def valor_receber
    salario = Remuneracao.where(funcionario_id: self.id).first.salario rescue 0
    return 0 if salario < 0.1
    salario_dia = salario / 22
    salario_hora = salario_dia / 8
    salario_minutos = salario_hora / 60

    minutos = 0
    Turno.where(funcionario_id: self.id).where("EXTRACT(MONTH FROM entrada) = ?", Time.zone.now.month).each do |turno|
      minutos += ((turno.saida - turno.entrada) / 60) #minutos no dia
    end

    minutos * salario_minutos
  end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario, local: true) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2>Confira os erros abaixo:</h2>

      <ul>
        <% funcionario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<div class="content-wrapper container">
  <h1>Editando Funcionario</h1>

  <%= render 'form', funcionario: @funcionario %>

  <%= link_to 'Mostrar', @funcionario %> |
  <%= link_to 'Voltar', funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <h1>Funcionarios</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Dias trabalhados</th>
        <th>Valor a receber</th>
        <th>Histórico do turno</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.dias_trabalhados %></td>
        <td>R$ <%= funcionario.valor_receber.round(2) %></td>
        <td><%= link_to 'Turnos', "#{turnos_path}?funcionario_id=#{funcionario.id}", class: "btn btn-primary" %></td>
        <td><%= link_to 'Mostrar', funcionario, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_funcionario_path(funcionario), class: "btn btn-warning" %></td>
        <td><%= link_to 'Apagar', funcionario, method: :delete, data: { confirm: 'Você tem certeza ??' }, class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo', new_funcionario_path, class: "btn btn-primary" %>
</div>

app/views/funcionarios/new.html.erb
<div class="content-wrapper container">
  <h1>Novo</h1>

  <%= render 'form', funcionario: @funcionario %>

  <%= link_to 'Voltar', funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<div class="content-wrapper container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nome:</strong>
    <%= @funcionario.nome %>
  </p>

  <%= link_to 'Editar', edit_funcionario_path(@funcionario) %> |
  <%= link_to 'Voltar', funcionarios_path %>
</div>